name: create vault-server
on:
  workflow_dispatch:
    inputs:
      action:
        type: string
        required: true
jobs:
  tf:
    runs-on: [self-hosted]
    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: terraform init
        run: |
           ls -l
        working-directory: ./misc-vault/v-server
