apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: sample
spec:
  selector:
    matchLabels:
      app: nginx
      testing: ab
      version: v2
  jwtRules:
    - issuer: "https://dev-0ximfmtawjyrzkgu.us.auth0.com/"
      jwksUri: "https://dev-0ximfmtawjyrzkgu.us.auth0.com/.well-known/jwks.json"
