apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx
  namespace: sample
spec:
  hosts:
    - "nginx.chaithanya.cloud"
  http:
    - route:
        - destination:
            host: nginx-svc
            subset: v1
          weight: 90
        - destination:
            host: nginx-svc
            subset: v2
          weight: 10


