apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
  labels:
    app: s1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - s1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: with-pod-affinity
      image: alpine
      command: ["sleep","10000"]

---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity2
  labels:
    app: s1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - s1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: with-pod-affinity
      image: alpine
      command: ["sleep","10000"]

---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity3
  labels:
    app: s1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - s1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: with-pod-affinity
      image: alpine
      command: ["sleep","10000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity4
  labels:
    app: s1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - s1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: with-pod-affinity
      image: alpine
      command: ["sleep","10000"]