apiVersion: v1
kind: Pod
metadata:
  name: with-node
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zones
                operator: DoesNotExist
  containers:
    - name: with-node-affinity
      image: alpine
      command: ["sleep","10000"]


