apiVersion: v1
kind: Pod
metadata:
  name: with-node
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: count
                operator: Gt
                values:
                  - "20"
  containers:
    - name: with-node-affinity
      image: alpine
      command: ["sleep","10000"]


