apiVersion: v1
kind: Pod
metadata:
  name: with-node
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                  - us-east-1a
                  - us-east-1b
  containers:
    - name: with-node-affinity
      image: alpine
      command: ["sleep","10000"]


