apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key:
                operator: In
                values:
                  - another-node-label-value
  containers:
    - name: with-node-affinity
      image: alpine
      command: ["sleep","10000"]
