---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.1.135/32
  policyTypes:
    - Ingress
    - Egress