---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx1
          - nginx2
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.1.135/32
        - ipBlock:
            cidr: 10.0.1.95/32
  policyTypes:
    - Ingress
    - Egress