apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    nginx: app1
spec:
  containers:
    - name: app1
      image: chaitu1812/aws-alb
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    nginx: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80