apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: project2
    alb.ingress.kubernetes.io/group.name: project2.group
    alb.ingress.kubernetes.io/group.order: '10'

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0b57ecbc29767f892, subnet-014bd2bf39258dc0b
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'

spec:
  rules:
    - host: "app1.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app1"
            backend:
              service:
                name: app1-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-ingress
  namespace: qa
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: project2
    alb.ingress.kubernetes.io/group.name: project2.group
    alb.ingress.kubernetes.io/group.order: '20'

spec:
  rules:
    - host: "app2.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app2"
            backend:
              service:
                name: app2-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3-ingress
  namespace: uat
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: project2
    alb.ingress.kubernetes.io/group.name: project2.group
    alb.ingress.kubernetes.io/group.order: '30'

spec:
  rules:
    - host: "app3.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app3"
            backend:
              service:
                name: app3-service
                port:
                  number: 80