apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project1-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: project2
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-01b34120f49bf5a7d, subnet-02b95e02658fcde81
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

spec:
  rules:
    - host: "app1.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app1"
            backend:
              service:
                name: app1-service
                port:
                  number: 80
    - host: "app2.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app2"
            backend:
              service:
                name: app2-service
                port:
                  number: 80
    - host: "app3.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/app2"
            backend:
              service:
                name: app3-service
                port:
                  number: 80
