name: create vault-server
on:
  workflow_dispatch:
    inputs:
      action:
        type: string
        required: true
jobs:
  tf:
    runs-on: [self-hosted]
    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: terraform init
        run: |
           terraform init
        working-directory: ./misc-vault/v-server

      - name: terraform plan
        run: |
          terraform plan
        working-directory: ./misc-vault/v-server

      - name: terraform apply
        if: ${{ inputs.action == "apply" }}
        run: |
          terraform apply -auto-approve
        working-directory: ./misc-vault/v-server

      - name: terraform destroy
        if: ${{ inputs.action == "destroy" }}
        run: |
          terraform destroy -auto-approve
        working-directory: ./misc-vault/v-server